version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: Chat_System_development
        MYSQL_PASSWORD: 12345678
    ports:
        - "3307:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "./Chat_System"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: Chat_System_development
      DB_PASSWORD: 12345678
      DB_HOST: db
      
