version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: Chat_System_development
        MYSQL_PASSWORD: 12345678
    ports:
        - "3307:3306"
  
  consumer:
    build: .
    command: bundle exec rails runner ./app/consumers/user-consumer.rb
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    hostname: 'localhost'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    hostname: 'localhost'



  app:
    build: .
    command:  bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./Chat_System"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq
    environment:
      DB_USER: root
      DB_NAME: Chat_System_development
      DB_PASSWORD: 12345678
      DB_HOST: db
      TokenSecret: 123456
      BUNNY_AMQP_ADDRESSES: 'localhost:5672'
      BUNNY_AMQP_USER: 'guest'
      BUNNY_AMQP_PASSWORD: 'guest'

  
      
